C PROGRAM FOR DIAGONALIZING A SYMMETRIC MATRIX USING JACOBI METHOD
C GAURAV RUDRA MALIK R.NO:23
	DIMENSION A(5,5),U(5,5),UT(5,5),S1(5,5),S(5,5)
	WRITE(*,*)'ENTER THE MATRIX ORDER, MAX:5'
	READ(*,*)N
50	WRITE(*,*)'ENTER THE MATRIX ELEMENTS FOR THE SYMMETRIC MATRIX'
	DO 2 I=1,N
	DO 1 J=1,N
	READ(*,*)A(I,J)
1	CONTINUE
2	CONTINUE
	DO 4 I=1,N
	DO 3 J=1,N
	IF(I.NE.J)THEN
	IF(A(I,J).NE.A(J,I))THEN
	WRITE(*,*)'DIAGONALIZATION NOT POSSIBLE'
	GOTO 50	
	ENDIF
	ENDIF
3	CONTINUE
4	CONTINUE
	WRITE(*,*)'ENTER THE NUMBER OF ITERATIONS'
	READ(*,*)M
	DO 70 IJ=1,M
C INITIALIZING THE TRANSFORMATION MATRIX AS IDENTITY
	DO 6 I=1,N
	U(I,I)=1.0
	DO 5 J=1,N
	IF(I.NE.J)THEN
	U(I,J)=0.0
	ENDIF
5	CONTINUE
6	CONTINUE
C LARGEST OFF DIAGONAL
	L=A(1,2)
	DO 8 I=2,N
	DO 7 J=2,I
	IF(A(I,J).GT.L)THEN
	L=A(I,J)
	II=I
	JJ=J
	ENDIF
7	CONTINUE
8	CONTINUE
	TH=0.5*ATAN((2*L)/(A(II,II)-A(JJ,JJ)))
	U(II,II)=COS(TH)
	U(JJ,JJ)=COS(TH)
	U(II,JJ)=SIN(TH)
	U(JJ,II)=SIN(TH)*(-1)
C TRANSPOSE	
	DO 10 I=1,N
	DO 9 J=1,N
	UT(I,J)=U(J,I)
9	CONTINUE
10	CONTINUE
C MULTIPLICATION		
	DO 13 I=1,N
	DO 12 J=1,N
	S1(I,J)=0.0
	DO 11 K=1,N
	S1(I,J)=S1(I,J) + A(I,K)*U(K,J)
11	CONTINUE
12	CONTINUE
13	CONTINUE
	DO 16 I=1,N
	DO 15 J=1,N
	S(I,J)=0.0
	DO 14 K=1,N
	S(I,J)=S(I,J) + UT(I,K)*S1(K,J)
14	CONTINUE
15	CONTINUE
16	CONTINUE
	DO 19 I=1,N
	DO 18 J=1,N
	A(I,J)=S(I,J)
18	CONTINUE
19	CONTINUE
70	CONTINUE
C RESULT DISPLAY
	WRITE(*,*)'THE DIAGONALIZED MATRIX IS:'
	DO 21 I=1,N
	WRITE(*,22)(A(I,J),j=1,n)
21	CONTINUE
22	FORMAT(3(F8.4,5X))
	STOP
	END


RESULT:

 ENTER THE MATRIX ORDER, MAX:5
3
 ENTER THE MATRIX ELEMENTS FOR THE SYMMETRIC MATRIX
2
1
0
1
1
2
0
2
1
 ENTER THE NUMBER OF ITERATIONS
50
 THE DIAGONALIZED MATRIX IS:
  2.0000        .0002        .0007
   .0000        .7500        .0000
   .0000        .0000      -1.0000


