C PROGRAM FOR MONTE CARLO INTEGRATION 
C GAURAV RUDRA MALIK, R.NO:23
	F(X)=X**2+1
	G(L)=MOD(1956*L + 178592,67529)
	WRITE(*,*)'INPUT THE UPPER AND LOWER LIMITS'
	READ(*,*)A,B
	WRITE(*,*)'ENTER THE NUMBER OF HITS'
	READ(*,*)N
	WRITE(*,*)'ENTER THE SEED'
	READ(*,*)Q
	DO 1 I=1,N
	Q=G(Q)
	X=Q/67529
	Y=A+(B-A)*X
	S=S+F(Y)/N
1	ENDDO
	WRITE(*,*)'THE INTEGRAL IS FOUND TO BE:',S
	STOP
	END

Result

 INPUT THE UPPER AND LOWER LIMITS
0
1
 ENTER THE NUMBER OF HITS
10000
 ENTER THE SEED
456
 THE INTEGRAL IS FOUND TO BE:  1.33563066

